import { COMMODITIES } from "../constants";
import { HospitalProps } from "../interfaces/hospital";

export const Hospitals: HospitalProps[] = [
  {
    marker: { latitude: 28.653611186441317, longitude: 77.18886095896161 },
    specialists: [
      "Allergists",
      "Immunologists",
      "Anesthesiologists",
      "Cardiologists",
      "Colon and Rectal Surgeons",
      "Critical Care Medicine Specialists",
      "Dermatologists",
      "Endocrinologists",
      "Emergency Medicine Specialists",
      "Nephrologists",
      "Neurologists",
      "Obstetricians and Gynecologists",
      "Oncologists",
      "Ophthalmologists",
      "Osteopaths",
      "Otolaryngologists",
      "Pathologists",
      "Pediatricians",
      "Physiatrists",
      "Plastic Surgeons",
      "Podiatrists",
      "Preventive Medicine Specialists",
      "Psychiatrists",
      "Pulmonologists",
      "Radiologists",
      "Rheumatologists",
      "Sleep Medicine Specialists",
      "Sports Medicine Specialists",
      "General Surgeons",
      "Urologists",
    ],
    contract_address: "0x01",
    name: "All India Institute of Medical Services",
    address: ["12/7", "ABC Street", "Navi Mumbai"],
    commodities: [
      {
        name: COMMODITIES.GATCH_BED,
        count: 50,
        available: 36,
        price: 1289900,
      },
      {
        name: COMMODITIES.E_SEMI_FOWLER_BED,
        count: 15,
        available: 4,
        price: 1962900,
      },
    ],
  },
  {
    name: "Fortris Hospital",
    contract_address: "0x02",
    address: [
      "730, Eastern Metropolitan Bypass",
      "East Kolkata Twp, Kolkata",
      "West Bengal 700107, India",
    ],
    commodities: [
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_20L,
        count: 100,
        available: 2,
        price: 650000,
      },
      {
        name: COMMODITIES.GATCH_BED,
        count: 20,
        available: 6,
        price: 1468000,
      },
    ],
    marker: { latitude: 22.845147420729994, longitude: 88.34965508011301 },
    specialists: [
      "Allergists",
      "Immunologists",
      "Dermatologists",
      "Endocrinologists",
      "Emergency Medicine Specialists",
      "Family Physicians",
      "Gastroenterologists",
      "Geriatric Medicine Specialists",
      "Hematologists",
      "Hospice and Palliative Medicine Specialists",
      "Nephrologists",
      "Neurologists",
      "Obstetricians and Gynecologists",
      "Oncologists",
      "Ophthalmologists",
      "Osteopaths",
      "Otolaryngologists",
      "Pathologists",
      "Pediatricians",
      "Physiatrists",
      "Plastic Surgeons",
      "Radiologists",
      "Rheumatologists",
      "Sleep Medicine Specialists",
      "Sports Medicine Specialists",
      "General Surgeons",
      "Urologists",
    ],
  },
  {
    name: "Indravats Apollo Hospital",
    contract_address: "0x03",
    address: [
      "Delhi Highway, Mathura Rd",
      "Sarita Vihar, New Delhi",
      "Delhi 110076, India",
    ],
    commodities: [
      {
        name: COMMODITIES.E_SEMI_FOWLER_BED,
        count: 25,
        available: 5,
        price: 2325000,
      },
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_20L,
        count: 20,
        available: 3,
        price: 550000,
      },
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_40L,
        count: 34,
        available: 21,
        price: 1468000,
      },
    ],
    marker: { latitude: 29.172921504348665, longitude: 77.21152055896157 },
    specialists: [
      "Cardiologists",
      "Colon and Rectal Surgeons",
      "Critical Care Medicine Specialists",
      "Dermatologists",
      "Endocrinologists",
      "Emergency Medicine Specialists",
      "Family Physicians",
      "Gastroenterologists",
      "Geriatric Medicine Specialists",
      "Hematologists",
      "Hospice and Palliative Medicine Specialists",
      "Infectious Disease Specialists",
      "Medical Geneticists",
      "Nephrologists",
      "Neurologists",
      "Obstetricians and Gynecologists",
      "Ophthalmologists",
    ],
  },
  {
    name: "Lilapati Hospital",
    contract_address: "0x04",
    address: [
      "Lilavati Hospital, A-791",
      "Bandra Reclamation Rd, Bandra West",
      "Mumbai, Maharashtra 400050, India",
    ],
    commodities: [
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_20L,
        count: 10,
        available: 8,
        price: 450000,
      },
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_40L,
        count: 15,
        available: 14,
        price: 990000,
      },
    ],
    marker: { latitude: 19.39566006583695, longitude: 72.88916244451774 },
    specialists: [
      "Allergists",
      "Immunologists",
      "Anesthesiologists",
      "Cardiologists",
      "Colon and Rectal Surgeons",
      "Critical Care Medicine Specialists",
      "Dermatologists",
      "Endocrinologists",
      "Emergency Medicine Specialists",
      "Family Physicians",
      "Gastroenterologists",
      "Geriatric Medicine Specialists",
      "Hematologists",
      "Hospice and Palliative Medicine Specialists",
      "Infectious Disease Specialists",
      "Internists",
      "Medical Geneticists",
      "Nephrologists",
      "Neurologists",
      "Obstetricians and Gynecologists",
      "Oncologists",
      "Ophthalmologists",
      "Osteopaths",
      "Otolaryngologists",
      "Pathologists",
      "Pediatricians",
      "Physiatrists",
      "Plastic Surgeons",
      "Podiatrists",
      "Preventive Medicine Specialists",
      "Psychiatrists",
      "Pulmonologists",
      "Radiologists",
      "Rheumatologists",
      "Sleep Medicine Specialists",
      "Sports Medicine Specialists",
      "General Surgeons",
      "Urologists",
    ],
  },
  {
    name: "Christian Medics College",
    contract_address: "0x05",
    address: ["IDA Scudder Rd", "Vellore", "Tamil Nadu 632004, India"],
    commodities: [
      {
        name: COMMODITIES.GATCH_BED,
        count: 32,
        available: 15,
        price: 1620450,
      },
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_40L,
        count: 12,
        available: 10,
        price: 643000,
      },
    ],
    marker: { latitude: 12.973025867389472, longitude: 79.1350994305809 },
    specialists: [
      "Allergists",
      "Immunologists",
      "Anesthesiologists",
      "Cardiologists",
      "Colon and Rectal Surgeons",
      "Critical Care Medicine Specialists",
      "Dermatologists",
      "Endocrinologists",
      "Emergency Medicine Specialists",
      "Family Physicians",
      "Gastroenterologists",
      "Geriatric Medicine Specialists",
      "Hematologists",
      "Hospice and Palliative Medicine Specialists",
      "Infectious Disease Specialists",
      "Internists",
      "Medical Geneticists",
      "Nephrologists",
      "Neurologists",
      "Obstetricians and Gynecologists",
      "Oncologists",
      "Ophthalmologists",
      "Osteopaths",
      "Otolaryngologists",
      "Pathologists",
      "Pediatricians",
      "Physiatrists",
      "Plastic Surgeons",
      "Podiatrists",
      "Preventive Medicine Specialists",
      "Psychiatrists",
      "Pulmonologists",
      "Radiologists",
      "Rheumatologists",
      "Sleep Medicine Specialists",
      "Sports Medicine Specialists",
      "General Surgeons",
      "Urologists",
    ],
  },
  {
    name: "Jawahar Institute of Medical Research",
    contract_address: "0x06",
    address: [
      "Jipmer Campus Rd, Gorimedu",
      "Dhanvantari Nagar",
      "Puducherry, 605006, India",
    ],
    commodities: [
      {
        name: COMMODITIES.E_SEMI_FOWLER_BED,
        count: 40,
        available: 17,
        price: 2120450,
      },
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_40L,
        count: 45,
        available: 12,
        price: 6430500,
      },
    ],
    marker: { latitude: 11.973856158426889, longitude: 79.79656656633209 },
    specialists: [
      "Allergists",
      "Immunologists",
      "Anesthesiologists",
      "Cardiologists",
      "Colon and Rectal Surgeons",
      "Critical Care Medicine Specialists",
      "Dermatologists",
      "Endocrinologists",
      "Emergency Medicine Specialists",
      "Family Physicians",
      "Gastroenterologists",
      "Geriatric Medicine Specialists",
      "Hematologists",
      "Hospice and Palliative Medicine Specialists",
      "Infectious Disease Specialists",
      "Internists",
      "Medical Geneticists",
      "Nephrologists",
      "Neurologists",
      "Obstetricians and Gynecologists",
      "Oncologists",
      "Ophthalmologists",
      "Osteopaths",
      "Otolaryngologists",
      "Pathologists",
      "Pediatricians",
      "Physiatrists",
      "Plastic Surgeons",
      "Podiatrists",
      "Preventive Medicine Specialists",
      "Psychiatrists",
      "Pulmonologists",
      "Radiologists",
      "Rheumatologists",
      "Sleep Medicine Specialists",
      "Sports Medicine Specialists",
      "General Surgeons",
      "Urologists",
    ],
  },
  {
    name: "Sankara Netralaya",
    contract_address: "0x07",
    address: [
      "No. 41, Old 18, College Rd",
      "Thousand Lights West, Nungambakkam",
      "Chennai, Tamil Nadu 600006, India",
    ],
    commodities: [
      {
        name: COMMODITIES.E_SEMI_FOWLER_BED,
        count: 40,
        available: 17,
        price: 2120450,
      },
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_40L,
        count: 45,
        available: 12,
        price: 6430500,
      },
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_20L,
        count: 60,
        available: 55,
        price: 999900,
      },
    ],
    marker: { latitude: 13.071701759918971, longitude: 80.2470700105511 },
    specialists: [
      "Allergists",
      "Immunologists",
      "Anesthesiologists",
      "Cardiologists",
      "Colon and Rectal Surgeons",
      "Critical Care Medicine Specialists",
      "Dermatologists",
      "Endocrinologists",
      "Emergency Medicine Specialists",
      "Family Physicians",
      "Gastroenterologists",
      "Geriatric Medicine Specialists",
      "Hematologists",
      "Hospice and Palliative Medicine Specialists",
      "Infectious Disease Specialists",
      "Internists",
      "Medical Geneticists",
      "Nephrologists",
      "Neurologists",
      "Obstetricians and Gynecologists",
      "Oncologists",
      "Ophthalmologists",
      "Osteopaths",
      "Otolaryngologists",
      "Pathologists",
      "Pediatricians",
      "Physiatrists",
      "Plastic Surgeons",
      "Podiatrists",
      "Preventive Medicine Specialists",
      "Psychiatrists",
      "Pulmonologists",
      "Radiologists",
      "Rheumatologists",
      "Sleep Medicine Specialists",
      "Sports Medicine Specialists",
      "General Surgeons",
      "Urologists",
    ],
  },
];

export const DetailedHospitals: HospitalProps[] = [
  {
    specialists: [
      "Anesthesiologists",
      "Colon and Rectal Surgeons",
      "Critical Care Medicine Specialists",
      "Emergency Medicine Specialists",
      "Obstetricians and Gynecologists",
      "Otolaryngologists",
    ],
    marker: { latitude: 12.820843681789723, longitude: 80.03778255530808 },
    contract_address: "0x09",
    name: "SRM Hospital",
    address: ["Potheri", "Kattankulathur", "Tamil Nadu 603203"],
    commodities: [
      {
        name: COMMODITIES.E_SEMI_FOWLER_BED,
        count: 17,
        available: 7,
        price: 2045000,
      },
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_20L,
        count: 20,
        available: 3,
        price: 550000,
      },
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_40L,
        count: 34,
        available: 21,
        price: 1468000,
      },
    ],
  },
  {
    specialists: [
      "Endocrinologists",
      "Emergency Medicine Specialists",
      "Family Physicians",
      "Gastroenterologists",
      "Geriatric Medicine Specialists",
      "Hospice and Palliative Medicine Specialists",
      "Obstetricians and Gynecologists",
      "Ophthalmologists",
      "Otolaryngologists",
    ],
    marker: { latitude: 12.820843681789723, longitude: 80.03778255530808 },
    contract_address: "0x08",
    name: "Appaulo Aspataal",
    address: ["12/7", "ABC Street", "Navi Mumbai"],
    commodities: [
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_20L,
        count: 10,
        available: 8,
        price: 450000,
      },
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_40L,
        count: 15,
        available: 14,
        price: 990000,
      },
    ],
  },
  {
    marker: { latitude: 28.653611186441317, longitude: 77.18886095896161 },
    specialists: [
      "Allergists",
      "Immunologists",
      "Anesthesiologists",
      "Cardiologists",
      "Colon and Rectal Surgeons",
      "Critical Care Medicine Specialists",
      "Dermatologists",
      "Endocrinologists",
      "Emergency Medicine Specialists",
      "Nephrologists",
      "Neurologists",
      "Obstetricians and Gynecologists",
      "Oncologists",
      "Ophthalmologists",
      "Osteopaths",
      "Otolaryngologists",
      "Pathologists",
      "Pediatricians",
      "Physiatrists",
      "Plastic Surgeons",
      "Podiatrists",
      "Preventive Medicine Specialists",
      "Psychiatrists",
      "Pulmonologists",
      "Radiologists",
      "Rheumatologists",
      "Sleep Medicine Specialists",
      "Sports Medicine Specialists",
      "General Surgeons",
      "Urologists",
    ],
    contract_address: "0x01",
    name: "All India Institute of Medical Services",
    address: ["12/7", "ABC Street", "Navi Mumbai"],
    commodities: [
      {
        name: COMMODITIES.GATCH_BED,
        count: 50,
        available: 36,
        price: 1289900,
      },
      {
        name: COMMODITIES.E_SEMI_FOWLER_BED,
        count: 15,
        available: 4,
        price: 1962900,
      },
    ],
  },
  {
    name: "Fortris Hospital",
    contract_address: "0x02",
    address: [
      "730, Eastern Metropolitan Bypass",
      "East Kolkata Twp, Kolkata",
      "West Bengal 700107, India",
    ],
    commodities: [
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_20L,
        count: 100,
        available: 2,
        price: 650000,
      },
      {
        name: COMMODITIES.GATCH_BED,
        count: 20,
        available: 6,
        price: 1468000,
      },
    ],
    marker: { latitude: 22.845147420729994, longitude: 88.34965508011301 },
    specialists: [
      "Allergists",
      "Immunologists",
      "Dermatologists",
      "Endocrinologists",
      "Emergency Medicine Specialists",
      "Family Physicians",
      "Gastroenterologists",
      "Geriatric Medicine Specialists",
      "Hematologists",
      "Hospice and Palliative Medicine Specialists",
      "Nephrologists",
      "Neurologists",
      "Obstetricians and Gynecologists",
      "Oncologists",
      "Ophthalmologists",
      "Osteopaths",
      "Otolaryngologists",
      "Pathologists",
      "Pediatricians",
      "Physiatrists",
      "Plastic Surgeons",
      "Radiologists",
      "Rheumatologists",
      "Sleep Medicine Specialists",
      "Sports Medicine Specialists",
      "General Surgeons",
      "Urologists",
    ],
  },
  {
    name: "Indravats Apollo Hospital",
    contract_address: "0x03",
    address: [
      "Delhi Highway, Mathura Rd",
      "Sarita Vihar, New Delhi",
      "Delhi 110076, India",
    ],
    commodities: [
      {
        name: COMMODITIES.E_SEMI_FOWLER_BED,
        count: 25,
        available: 5,
        price: 2325000,
      },
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_20L,
        count: 20,
        available: 3,
        price: 550000,
      },
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_40L,
        count: 34,
        available: 21,
        price: 1468000,
      },
    ],
    marker: { latitude: 29.172921504348665, longitude: 77.21152055896157 },
    specialists: [
      "Cardiologists",
      "Colon and Rectal Surgeons",
      "Critical Care Medicine Specialists",
      "Dermatologists",
      "Endocrinologists",
      "Emergency Medicine Specialists",
      "Family Physicians",
      "Gastroenterologists",
      "Geriatric Medicine Specialists",
      "Hematologists",
      "Hospice and Palliative Medicine Specialists",
      "Infectious Disease Specialists",
      "Medical Geneticists",
      "Nephrologists",
      "Neurologists",
      "Obstetricians and Gynecologists",
      "Ophthalmologists",
    ],
  },
  {
    name: "Lilapati Hospital",
    contract_address: "0x04",
    address: [
      "Lilavati Hospital, A-791",
      "Bandra Reclamation Rd, Bandra West",
      "Mumbai, Maharashtra 400050, India",
    ],
    commodities: [
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_20L,
        count: 10,
        available: 8,
        price: 450000,
      },
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_40L,
        count: 15,
        available: 14,
        price: 990000,
      },
    ],
    marker: { latitude: 19.39566006583695, longitude: 72.88916244451774 },
    specialists: [
      "Allergists",
      "Immunologists",
      "Anesthesiologists",
      "Cardiologists",
      "Colon and Rectal Surgeons",
      "Critical Care Medicine Specialists",
      "Dermatologists",
      "Endocrinologists",
      "Emergency Medicine Specialists",
      "Family Physicians",
      "Gastroenterologists",
      "Geriatric Medicine Specialists",
      "Hematologists",
      "Hospice and Palliative Medicine Specialists",
      "Infectious Disease Specialists",
      "Internists",
      "Medical Geneticists",
      "Nephrologists",
      "Neurologists",
      "Obstetricians and Gynecologists",
      "Oncologists",
      "Ophthalmologists",
      "Osteopaths",
      "Otolaryngologists",
      "Pathologists",
      "Pediatricians",
      "Physiatrists",
      "Plastic Surgeons",
      "Podiatrists",
      "Preventive Medicine Specialists",
      "Psychiatrists",
      "Pulmonologists",
      "Radiologists",
      "Rheumatologists",
      "Sleep Medicine Specialists",
      "Sports Medicine Specialists",
      "General Surgeons",
      "Urologists",
    ],
  },
  {
    name: "Christian Medics College",
    contract_address: "0x05",
    address: ["IDA Scudder Rd", "Vellore", "Tamil Nadu 632004, India"],
    commodities: [
      {
        name: COMMODITIES.GATCH_BED,
        count: 32,
        available: 15,
        price: 1620450,
      },
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_40L,
        count: 12,
        available: 10,
        price: 643000,
      },
    ],
    marker: { latitude: 12.973025867389472, longitude: 79.1350994305809 },
    specialists: [
      "Allergists",
      "Immunologists",
      "Anesthesiologists",
      "Cardiologists",
      "Colon and Rectal Surgeons",
      "Critical Care Medicine Specialists",
      "Dermatologists",
      "Endocrinologists",
      "Emergency Medicine Specialists",
      "Family Physicians",
      "Gastroenterologists",
      "Geriatric Medicine Specialists",
      "Hematologists",
      "Hospice and Palliative Medicine Specialists",
      "Infectious Disease Specialists",
      "Internists",
      "Medical Geneticists",
      "Nephrologists",
      "Neurologists",
      "Obstetricians and Gynecologists",
      "Oncologists",
      "Ophthalmologists",
      "Osteopaths",
      "Otolaryngologists",
      "Pathologists",
      "Pediatricians",
      "Physiatrists",
      "Plastic Surgeons",
      "Podiatrists",
      "Preventive Medicine Specialists",
      "Psychiatrists",
      "Pulmonologists",
      "Radiologists",
      "Rheumatologists",
      "Sleep Medicine Specialists",
      "Sports Medicine Specialists",
      "General Surgeons",
      "Urologists",
    ],
  },
  {
    name: "Jawahar Institute of Medical Research",
    contract_address: "0x06",
    address: [
      "Jipmer Campus Rd, Gorimedu",
      "Dhanvantari Nagar",
      "Puducherry, 605006, India",
    ],
    commodities: [
      {
        name: COMMODITIES.E_SEMI_FOWLER_BED,
        count: 40,
        available: 17,
        price: 2120450,
      },
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_40L,
        count: 45,
        available: 12,
        price: 6430500,
      },
    ],
    marker: { latitude: 11.973856158426889, longitude: 79.79656656633209 },
    specialists: [
      "Allergists",
      "Immunologists",
      "Anesthesiologists",
      "Cardiologists",
      "Colon and Rectal Surgeons",
      "Critical Care Medicine Specialists",
      "Dermatologists",
      "Endocrinologists",
      "Emergency Medicine Specialists",
      "Family Physicians",
      "Gastroenterologists",
      "Geriatric Medicine Specialists",
      "Hematologists",
      "Hospice and Palliative Medicine Specialists",
      "Infectious Disease Specialists",
      "Internists",
      "Medical Geneticists",
      "Nephrologists",
      "Neurologists",
      "Obstetricians and Gynecologists",
      "Oncologists",
      "Ophthalmologists",
      "Osteopaths",
      "Otolaryngologists",
      "Pathologists",
      "Pediatricians",
      "Physiatrists",
      "Plastic Surgeons",
      "Podiatrists",
      "Preventive Medicine Specialists",
      "Psychiatrists",
      "Pulmonologists",
      "Radiologists",
      "Rheumatologists",
      "Sleep Medicine Specialists",
      "Sports Medicine Specialists",
      "General Surgeons",
      "Urologists",
    ],
  },
  {
    name: "Sankara Netralaya",
    contract_address: "0x07",
    address: [
      "No. 41, Old 18, College Rd",
      "Thousand Lights West, Nungambakkam",
      "Chennai, Tamil Nadu 600006, India",
    ],
    commodities: [
      {
        name: COMMODITIES.E_SEMI_FOWLER_BED,
        count: 40,
        available: 17,
        price: 2120450,
      },
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_40L,
        count: 45,
        available: 12,
        price: 6430500,
      },
      {
        name: COMMODITIES.OXYGEN_CYLINDERS_20L,
        count: 60,
        available: 55,
        price: 999900,
      },
    ],
    marker: { latitude: 13.071701759918971, longitude: 80.2470700105511 },
    specialists: [
      "Allergists",
      "Immunologists",
      "Anesthesiologists",
      "Cardiologists",
      "Colon and Rectal Surgeons",
      "Critical Care Medicine Specialists",
      "Dermatologists",
      "Endocrinologists",
      "Emergency Medicine Specialists",
      "Family Physicians",
      "Gastroenterologists",
      "Geriatric Medicine Specialists",
      "Hematologists",
      "Hospice and Palliative Medicine Specialists",
      "Infectious Disease Specialists",
      "Internists",
      "Medical Geneticists",
      "Nephrologists",
      "Neurologists",
      "Obstetricians and Gynecologists",
      "Oncologists",
      "Ophthalmologists",
      "Osteopaths",
      "Otolaryngologists",
      "Pathologists",
      "Pediatricians",
      "Physiatrists",
      "Plastic Surgeons",
      "Podiatrists",
      "Preventive Medicine Specialists",
      "Psychiatrists",
      "Pulmonologists",
      "Radiologists",
      "Rheumatologists",
      "Sleep Medicine Specialists",
      "Sports Medicine Specialists",
      "General Surgeons",
      "Urologists",
    ],
  },
];
